[TOC]

## 예외 처리(Exception Handling)

코드 실행 중 예기치 못한 에러가 발생 했을 때, 프로그램이 중단되거나 비정상적인 결과를 초래할 수 있다.

프로그래머는 예외를 처리를 통해 코드의 실행 흐름을 복구 할 수 있어야 한다.

> 🔍 **에러(Error)와 예외(Exception)의 차이**
>
> 프로그램을 실행할 때 오작동이나 비정상적으로 종료되는 원인을 오류 또는 에러라고 한다.
>
> **에러(Error)** : 메모리 부족, 스택오버플로우 등 발생하게 되면 복구하기 쉽지 않은 심각한 오류  
> **예외(Exception)** : 발생하더라도 수습할 수 있을 정도의 심각하지 않은 오류

### 예외 처리 방법

#### 1. try-catch-finally 문

```js
try {
  // 예외가 발생할 가능성이 있는 코드
  const result = someFunction();
  console.log(result);
} catch (error) {
  // try 블록에서 예외가 발생했을 때 실행되는 코드
  console.error(error);
} finally {
  // 예외 발생 여부와 상관 없이 실행되는 코드
  console.log('finally block executed');
}
```

- **try** 
  - 에러가 났을 때 원상 복구를 시도할 코드, 에러 발생시 코드의 실행 흐름이 catch 블록으로 옮겨간다. 

- **catch**
  - 에러에 대한 정보를 담고 있는 객체(e 매개변수)를 사용할 수 있다.
  - `e.name` : 에러 이름  
    `e.message` : 에러 상세 내용을 담고 있는 문자 메시지  
    `e.stack` : 현재 호출 스택. 에러를 유발한 중첩 호출들의 순서 정보를 가진 문자열로 디버깅 목적으로 사용된다.
- **finally**
  - try블록 안에서의 에러 발생 여부와 관계 없이 무조건 실행되어야 하는 코드
  - return, break, continue등으로 코드의 실행 흐름이 즉시 이동되더라도 무조건 실행된다.
  - 보통 catch와 같이 쓰인다.
  - 에러가 안 났을 때: try - finally
  - 에러가 났을 때: try - 에러 발생 - catch - finally

#### 2. 예외 던지기 (throw)

예외를 강제로 발생시켜야 할 경우가 생길 때는 throw를 사용한다. 

개발자가 예외를 던지면, 예외 객체가 생성되고, 이 객체는 프로그램 실행 중에 catch 블록에서 처리되게 된다.

예외 객체는 `new Error('에러 메세지')` 형식으로 생성한다.  
예외 객체를 생성할 때는, 보통 예외에 대한 설명을 포함한 메시지를 함께 전달하는 편이다.

Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다.  
즉, 에러 객체 생성과 에러 발생은 의미가 다르다.

```js
try {
  new Error("something wrong"); // 에러 객체를 생성한다고 에러가 발생하는 것은 아니다.
    
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
    throw new Error('짝수가 아닙니다.');
  }
  
} catch (e) {
  alert(e.message);
}
// 3을 입력할 경우
// Error: 짝수가 아닙니다.
```

<br>

### 비동기 예외 처리

비동기 처리 코드(Promise, Async/await)에서의 에러 처리는 일반적인 에러 처리와는 약간 다르다.

try - catch는 기본적으로 동기적으로 동작한다. 비동기 작업은 콜스택에 들어가는 것이 아니라 작업 큐에서 대기했다가 콜스택이 비어있게 되면 콜스택으로 들어와 실행된다. 따라서 setTimeout처럼 비동기 작업은 try-catch를 떠난 다음에 실행되기 때문에  예외가 발생하는 시점이 try가 싸고 있는 시간이 일치하지 않게 된다. 따라서 try catch 구문으로 에러를 잡을 수 없다.

#### setTimeout 예외처리

스케줄 된 함수 내부의 예외를 잡으려면, try - catch를 반드시 함수 내부에 구현해야 한다.

```js
setTimeout(function() {
  try {
    noSuchVariable; // 에러 상황
  } catch {
    alert( "에러를 잡았다!" );
  }
}, 1000);
```

#### Promise 예외 처리

```js
const sleep = function(sec){
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            reject('Error 발생')
        }, 1000 * sec)
    })
}

// 1. Promise의 .then() 이용하기
sleep(3).then(
	(result) => { //Reslolve 되었을 때의 처리
		console.log(result);
  	},(e) => { //Reject 되었을 때의 처리
		console.log(e);
  	}
);

// 2. Promise의 .catch() 이용
sleep(3).catch((e) => {
      console.log(e);
});
```

#### async/await 예외 처리

async함수 역시 Promise를 리턴하기 때문에 Promis 예외처리와 비슷하다.

async와 await을 함께 쓴다면 await으로 인해 `try-catch` 문의 시점과 에러가 발생하는 시점이 일치하기 때문에 `try-catch` 문도 사용 가능하다.

```js
// 1. .catch() 이용
async function myFunction(){
    throw 'Error!';
}

myFunction().catch(e => console.log(e));

// 2. try-catch 방식(async와 await를 함께 쓴 경우에만 가능)
const sleep = function (sec) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      reject("Error 발생");
    }, 1000 * sec);
  });
};

const myFunction = async function () {
  try {
    const result = await sleep(3);
  } catch (e) {
    console.log(e);
  }
};

myFunction();
```

<br>

## 모듈

모듈이란, 모듈은 프로그램을 구성하는 구성 요소의 일부를 말한다.

즉, 애플리케이션을 작게 파일로 분리해서 관리할 때, 분리된 파일 각각을 **모듈**이라고 말한다.  
보통 클래스 하나 + 특정한 목적을 가지는 복수의 함수로 구성된 라이브러리 하나 정도로 구성된다.

### 모듈 사용 장점

- **용이성 증대 및 복잡성 감소(유지보수성)**
  - 기능들이 모듈화가 잘 되어있다면, 의존성을 그만큼 줄일 수 있기 때문에 어떤 기능을 개선한다거나 수정할 때 훨씬 편하게 할 수 있다.
- **모듈 재사용성**
  - 똑같은 코드를 반복하지 않고 모듈로 분리시켜서 필요할 때마다 사용할 수 있다.
- 오류의 파급효과를 최소화

### 자바스크립트에서 모듈

스크립트의 크기가 점차 커지고 기능이 복잡해지자 자바스크립트 커뮤니티는 라이브러리를 만들어서 필요한 모듈을 언제든지 불러올 수 있도록 하거나 모듈로 쉽게 분리 할 수 있는 방법들을 제시했다.

- **AMD** : 가장 오래된 모듈 시스템 중 하나. require.js라는 라이브러리를 통해 처음 개발.

- **CommonJS** : Node.js 서버를 위해 만들어짐

- **UMD** : AMD와 CommonJS와 같은 모듈 시스템을 함께 사용하기 위해 등장

- **ES6 방식** : import와 export 구문을 사용하는 방식이다.

#### ES6(ES2015) 방식

`import` 와 `export` 구문을 사용하는 방식이다. 

- `export` : 변수나 함수 앞에 붙이면 외부 모듈에서 해당 변수나 함수에 접근할 수 있다.
- `import` : 외부 모듈의 기능을 가져올 수 있다.

> 🔍 `import`는 babel이 필요하다!?
>
> import는 ES6에서 도입되었기 때문에  babel과 같은 ES6 코드를 변환해주는 도구 없이는 사용하지 못한다. 
>
> 브라우저가 지원하는 것이 아니기 때문에 Babel의 `@babel/plugin-transform-modules-commonjs` 를 통해 변환시켜서 사용한다. 

`export` 로 내보내는 방식과 그에 따라 어떻게 `import` 로 불러오는 방식이 다르다.

```js
// 1. named export를 사용하는 경우 : {} 로 묶어서 가져와야 한다. 
export const B = () => {};
import {B} from 'moduleB';

// 2. default export 를 사용하는 경우 : → 그대로 사용가능
export A = () => {};
export default A;

import A from 'moduleA';
```

<br>

---

**참고**

[[JS] 자바스크립트 예외처리](https://ebbnflow.tistory.com/268)

[자바스크립트의 예외 처리(Exception) - Inpa Dev ‍ - 티스토리](https://inpa.tistory.com/entry/JS-📚-예외-처리)

[[JS] 자바스크립트 비동기 예외처리(Promise, async, await)](https://jonyo.tistory.com/158)

[[JavaScript] 모듈이란? - 팔만코딩경 Mobile](https://80000coding.oopy.io/a9e13d5e-e858-40f5-a80f-dbb50d0b65f4)

[[JS] 모듈에 대한 이해와 사용법](https://baeharam.netlify.app/posts/javascript/module)

